# Generated by Django 5.0.6 on 2024-07-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdereDetail',
            new_name='OrderDetail',
        ),
    ]
